# This file was generated by GoReleaser. DO NOT EDIT.
cask "aes256cli" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "b633a3c1dc8dc25c2ce6114fc25012be6ac489115ab22b09833fa18231364df4"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4eb1fa0721de8949989b82807e8f78a887cb77034f52bb36570dbe8271441b5"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cf1836080bacc412e2bf814670c2e862262d715486d2b76c22f09d84dc7f1fd4"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "44557777a735310cb38dd70226003982991f00ab633ff400c1efd0aad8cddd8c"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aes256cli"
  desc "Encrypt and decrypt files with AES-256"
  homepage "https://github.com/ro-tex/aes256cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aes256cli"

  postflight_steps do
    on_macos do
      # The binary is not signed, so remove the quarantine attribute
      # to keep macOS Gatekeeper from blocking it.
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/aes256cli"]
    end
  end

  # No zap stanza required
end
