# This file was generated by GoReleaser. DO NOT EDIT.
cask "aes256cli" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "e0682bb0a8a5251757a2292888c9ae94617f758aecaf5e38b9ec795f34cd3117"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a8ba985dae177561860682ff88e5641559e24089e8ec18cb722322dd2e8895ba"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7ee1522a55fb81a84d595c6a872939ead477da2b7741e1f7288c08a28996ca85"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "03cd1d29ccf1dd4a5f1e71266d9c4b306e7ad814b30c513b03ac53e8f795ae87"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aes256cli"
  desc "A simple file encrypt/decrypt tool using AES-256."
  homepage "https://github.com/ro-tex/aes256cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aes256cli"

  postflight do
    if OS.mac?
      # The binary is not signed, so remove the quarantine attribute
      # to keep macOS Gatekeeper from blocking it.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aes256cli"]
    end
  end

  # No zap stanza required
end
