# This file was generated by GoReleaser. DO NOT EDIT.
cask "aes256cli" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "a7e375c313c23f7164338fc3aff7726edec146dee3b9a016f922bfe452ba822c"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4bf11db6ba011986bbda8525b04a1ca07fa366eb05e22029dc2a3b5aef99df7"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d79a9b14d7cf7237fb37f77ee925b51e892ed53aef8aecd1bc2638c9f8630c9"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8a771b00310c175278b01e973c6a7a5664bb0c4fb639a9d131af19ce813cabec"
      url "https://github.com/ro-tex/aes256cli/releases/download/v#{version}/aes256cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aes256cli"
  desc "A simple file encrypt/decrypt tool using AES-256."
  homepage "https://github.com/ro-tex/aes256cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aes256cli"

  postflight do
    if OS.mac?
      # The binary is not signed, so remove the quarantine attribute
      # to keep macOS Gatekeeper from blocking it.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aes256cli"]
    end
  end

  # No zap stanza required
end
